config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :series do
    resources :seasons, except: [:index] do
      resources :rounds, except: [:index] do
        member do
          get 'starting_teams' => 'rounds#edit_teams'
          patch 'starting_teams' => 'rounds#update_teams'
          get 'qualification' => 'rounds#show_qualification'
          get 'qualification_group_result/:qualification_group_result_id' => 'rounds#edit_qualification_group_result', as: :qualification_group_result
          patch 'qualification_group_result/:qualification_group_result_id' => 'rounds#update_qualification_group_result'
          get 'qualification_generate_result' => 'rounds#generate_qualification_result'
          get 'qualification_result/:qualification_result_id' => 'rounds#edit_qualification_result', as: :qualification_result
          patch 'qualification_result/:qualification_result_id' => 'rounds#update_qualification_result'
          get 'races' => 'rounds#show_races'
          get 'race_result/:race_result_id' => 'rounds#edit_race_result', as: :race_result
          patch 'race_result/:race_result_id' => 'rounds#update_race_result'
          get 'carts' => 'rounds#show_carts'
          get 'cart/:cart_id' => 'rounds#edit_cart', as: :cart
          patch 'cart/:cart_id' => 'rounds#update_cart'
          delete 'cart/:cart_id' => 'rounds#destroy_cart'
          get 'new_cart' => 'rounds#new_cart', as: :new_cart
          post 'new_cart' => 'rounds#create_cart'
          get 'results' => 'rounds#show_results'
        end
      end
      resources :teams, except: [:show]
    end
  end
  devise_for :users, skip: [:confirmation, :passwords, :registrations]
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/season.rb
# frozen_string_literal: true

class Season < ApplicationRecord
  validates_uniqueness_of :name, scope: :serie
  belongs_to :serie
  has_many :rounds, dependent: :destroy
  has_many :teams, dependent: :destroy
end

app/controllers/seasons_controller.rb
# frozen_string_literal: true

class SeasonsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @rounds = @season.rounds
    
    @content_0 = '<div class="d-flex justify-content-between">' +
        '<h5 class="mb-1">'
    @content_1 = '</h5><small style="allign: right;">Termin: '
    @content_2 = '</small></div><p class="mb-1">'
    @content_3 = '</p><small>Cena: '
    @content_4 = '</small>'
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)
    
    @season.serie = Serie.find(params[:series_id])
    
    respond_to do |format|
      if @season.save
        format.html {
          redirect_to series_season_path(@season.serie, @season),
          notice: 'Dodano sezon.'
        }
        format.json {
          render :show,
          status: :created,
          location: @season
        }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
	rescue ActiveRecord::RecordInvalid
		respond_to do |format|
		  flash.now.alert = @season.errors.full_messages.join('<br />').html_safe
		  return render :new
		end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html {
          redirect_to series_season_path(@season.serie, @season),
          notice: 'Zmieniono nazwę sezonu.'
        }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html {
          flash.now.alert = @serie.errors.full_messages.join('<br />').html_safe
          render :edit
        }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
	rescue ActiveRecord::RecordNotUnique
		respond_to do |format|
			flash.now.alert = 'Sezon o tej nazwie już istnieje.'
			return render :edit
		end
	rescue ActiveRecord::RecordInvalid
		respond_to do |format|
		  flash.now.alert = @season.errors.full_messages.join('<br />').html_safe
		  return render :edit
		end
	end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    serie = @season.serie
    @season.destroy
    respond_to do |format|
      format.html {
        redirect_to series_path(serie),
        notice: 'Sezon został usunięty.'
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name)
    end
end

app/helpers/seasons_helper.rb
# frozen_string_literal: true

module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_with(model: season, local: true) do |form| %>
  <% if season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
        <% season.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :series_id %>
    <%= form.text_field :series_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<% errors = @season.errors.messages %>
<% saved_season = Season.find(@season.id) %>
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"), series_season_path(@season.serie),
          method: :get, class: "btn btn-light btn-sm" %>
        <%= saved_season.name %> - edycja
      </div>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= form_for @season, url: series_season_path(@season.serie, @season),
            html: { method: :patch } do |f| %>
          <div class="form-group">
            <%= f.label :name, "Nazwa sezonu" %>
            <%= f.text_field :name, class: "form-control" %>
            <% if errors[:name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
          </div>
          
          <div style="text-align: center;">
            <%= f.submit "Zapisz", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to "Wróć", series_path(params[:series_id]) %>
      </div>
      <div class="col-auto m button-header">
        <%= button_to "Usuń sezon", series_season_path(@season.serie, @season),
            method: :delete, class: "btn btn-danger btn-sm",
            data: { confirm: "Czy na pewno chcesz usunąć sezon <strong>" +
                saved_season.name + "</strong>?" } %>
      </div>
  </div>
</div>

app/views/seasons/new.html.erb
<% errors = @season.errors.messages %>
<div class="card card-app">
  <h5 class="card-header">
    Nowy sezon
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        
        <%= form_for @season, url: series_seasons_path,
            html: { method: :post } do |f| %>
          <div class="form-group">
            <%= f.label :name, "Nazwa sezonu" %>
            <%= f.text_field :name, class: "form-control" %>
            <% if errors[:name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
          </div>
          
          <div style="text-align: center;">
            <%= f.submit "Utwórz", class: "btn btn-success" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
  <div class="card-footer text-muted">
    <%= link_to "Wróć", series_path(params[:series_id]) %>
  </div>
</div>

app/views/seasons/show.html.erb
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"), series_path(@season.serie),
            method: :get, class: "btn btn-light btn-sm" %>
        <%= @season.serie.name + " - " + @season.name %>
      </div>
      <div class="col-auto m button-header">
        <%= button_to "Zespoły",
            series_season_teams_path(@season.serie, @season),
            method: :get, class: "btn btn-primary btn-sm" %>
      </div>
      <% if user_signed_in? %>
        <div class="col-auto m button-header">
          <%= button_to "Dodaj rundę",
              new_series_season_round_path(@season.serie, @season),
              method: :get, class: "btn btn-success btn-sm" %>
        </div>
        <div class="col-auto m button-header">
          <%= button_to "Edytuj sezon",
              edit_series_season_path(@season.serie, @season),
              method: :get, class: "btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="list-group">
      <% @rounds.sort_by{ |r| r.start_time }.each do |round| %>
        <% content = @content_0 + round.name + @content_1 +
            round.start_time.strftime("%Y-%m-%d %H:%M") + @content_2 +
            round.track_name + @content_3 +
            round.price + @content_4 %>
        <%= link_to content.html_safe,
            series_season_round_path(round.season.serie, round.season, round),
            method: :get, class: "list-group-item list-group-item-action" %>
      <% end %>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to "Wróć", :back %>
  </div>
</div>