config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :series do
    resources :seasons, except: [:index] do
      resources :rounds, except: [:index] do
        member do
          get 'starting_teams' => 'rounds#edit_teams'
          patch 'starting_teams' => 'rounds#update_teams'
          get 'qualification' => 'rounds#show_qualification'
          get 'qualification_group_result/:qualification_group_result_id' => 'rounds#edit_qualification_group_result', as: :qualification_group_result
          patch 'qualification_group_result/:qualification_group_result_id' => 'rounds#update_qualification_group_result'
          get 'qualification_generate_result' => 'rounds#generate_qualification_result'
          get 'qualification_result/:qualification_result_id' => 'rounds#edit_qualification_result', as: :qualification_result
          patch 'qualification_result/:qualification_result_id' => 'rounds#update_qualification_result'
          get 'races' => 'rounds#show_races'
          get 'race_result/:race_result_id' => 'rounds#edit_race_result', as: :race_result
          patch 'race_result/:race_result_id' => 'rounds#update_race_result'
          get 'carts' => 'rounds#show_carts'
          get 'cart/:cart_id' => 'rounds#edit_cart', as: :cart
          patch 'cart/:cart_id' => 'rounds#update_cart'
          delete 'cart/:cart_id' => 'rounds#destroy_cart'
          get 'new_cart' => 'rounds#new_cart', as: :new_cart
          post 'new_cart' => 'rounds#create_cart'
          get 'results' => 'rounds#show_results'
        end
      end
      resources :teams, except: [:show]
    end
  end
  devise_for :users, skip: [:confirmation, :passwords, :registrations]
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/round.rb
# frozen_string_literal: true

class Round < ApplicationRecord
  validates_uniqueness_of :name, scope: :season
  validates :price, format: { with: /\A\d+(,\d{1,2})? [A-Z]{3}\z/,
    message: 'musi zawierać wartość w formacie "12 GBP", "54,95 CZK" itp.' }
  belongs_to :season
  has_many :team_rounds, dependent: :destroy
  has_many :teams, through: :team_rounds
  has_one :qualification, dependent: :destroy
  has_many :races, dependent: :destroy
  has_many :round_results, dependent: :destroy
  has_many :race_groups, dependent: :destroy
  has_many :carts, dependent: :destroy
end

app/controllers/rounds_controller.rb
# frozen_string_literal: true

class RoundsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :edit_teams,
                                              :show_qualification, :show_races, :show_results, :show_carts]
  before_action :set_round, only: [:show, :edit, :update, :destroy,
                                   :edit_teams, :update_teams, :show_qualification,
                                   :edit_qualification_group_result, :update_qualification_group_result,
                                   :generate_qualification_result, :edit_qualification_result,
                                   :update_qualification_result, :show_races, :edit_race_result,
                                   :update_race_result, :show_results, :show_carts, :new_cart,
                                   :create_cart, :edit_cart, :update_cart, :destroy_cart]

  # GET /rounds/1
  # GET /rounds/1.json
  def show; end

  # GET /rounds/new
  def new
    @round = Round.new
    @round.start_time = Time.zone.now.strftime('%Y-%m-%d %H:%M')
    @round.price = '110 PLN'
    @round.max_number_of_carts = 10
  end

  # GET /rounds/1/edit
  def edit; end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    @round.season = Season.find(params[:season_id])

    respond_to do |format|
      if @round.save
        format.html {
          redirect_to series_season_round_path(
                        @round.season.serie, @round.season, @round
                      ),
                      notice: 'Dodano rundę.'
        }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      flash.now.alert = @season.errors.full_messages.join('<br />').html_safe
      return render :new
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html {
          redirect_to series_season_round_path(@round.season.serie, @round.season, @round),
                      notice: 'Zaktualizowano rundę.'
        }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html {
          flash.now.alert = @round.errors.full_messages.join('<br />').html_safe
          render :edit
        }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordNotUnique
    respond_to do |format|
      flash.now.alert = 'Runda o tej nazwie już istnieje.'
      return render :edit
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      flash.now.alert = @season.errors.full_messages.join('<br />').html_safe
      return render :edit
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    season = @round.season
    serie = season.serie
    @round.destroy
    respond_to do |format|
      format.html {
        redirect_to series_season_path(serie, season),
                    notice: 'Runda została usunięta.'
      }
      format.json { head :no_content }
    end
  end

  def edit_teams
    @season_teams = @round.season.teams
    @teams = @round.teams
  end

  def update_teams
    params_teams = params[:teams]
    @round.season.teams.each do |season_team|
      if not(params_teams.nil?) &&
          params_teams.keys.include?(season_team.id.to_s)
        if ActiveRecord::Type::Boolean.new.cast(
              params_teams[season_team.id.to_s][:starting]
            ) && not(@round.teams.include? season_team)
          @round.teams << season_team
        end
      else
        @round.teams.delete(season_team)
      end
    end
    @round.save!

    respond_to do |format|
      format.html {
        redirect_to starting_teams_series_season_round_path(
                      @round.season.serie, @round.season, @round
                    ),
                    notice: 'Lista startowa została zaktualizowana.'
      }
      format.json { head :no_content }
    end
  end

  def show_qualification
    if @round.teams.size > 0
      if @round.qualification.nil? && user_signed_in?
        create_qualification
      end

      unless @round.qualification.nil?
        @qualification = @round.qualification

        @season = @round.season

        respond_to do |format|
          return render :qualification
        end
      end
    end

    if user_signed_in?
      flash[:alert] = 'Brak zgłoszonych zespołów.'
    end
    redirect_to starting_teams_series_season_round_path(
                  @round.season.serie, @round.season, @round
                )
  end

  def edit_qualification_group_result
    @qualification_group_result =
      QualificationGroupResult.find(params[:qualification_group_result_id])
  end

  def update_qualification_group_result
    @qualification_group_result =
      QualificationGroupResult.find(params[:qualification_group_result_id])
    time = params[:qualification_group_result][:time]
    @qualification_group_result.time = if time != ''
                                         if time.include? ':'
                                          '00:' + time
                                         else
                                           '00:00:' + time
                                         end
                                       else
                                         '00:00:00,000'
                                       end
    respond_to do |format|
      if @qualification_group_result.save
        format.html {
          redirect_to qualification_series_season_round_path(@round.season.serie, @round.season, @round),
                      notice: 'Zaktualizowano czas.'
        }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html {
          flash.now.alert = @serie.errors.full_messages.join('<br />').html_safe
          render :edit_qualification_group_result
        }
        format.json { render json: @qualification_group_result.errors, status: :unprocessable_entity }
      end
    end
  end

  def generate_qualification_result
    qualification = @round.qualification
    qualification_results = []

    qualification.qualification_groups.each do |group|
      group.qualification_group_results.each do |result|
        qualification_result = QualificationResult.new
        qualification_result.qualification = qualification
        qualification_result.team = result.team
        qualification_result.time = result.time

        qualification_results << qualification_result
      end
    end

    qualification_results.sort_by! { |r| r.time.nil? ? Time.at(-60 * 60) : r.time }

    last_position = position = 1
    last_time = Time.at(-60 * 60)

    qualification_results.each do |result|
      if result.time == last_time
        result.position = last_position
      else
        last_position = result.position = position
      end
      position += 1
      last_time = result.time
    end

    qualification_results.each do |result|
      result.save!
    end

    flash[:success] = 'Wygenerowano wstępne wyniki.'
    redirect_to qualification_series_season_round_path(
                  @round.season.serie, @round.season, @round
                )
  end

  def edit_qualification_result
    @qualification_result =
      QualificationResult.find(params[:qualification_result_id])
  end

  def update_qualification_result
    @qualification_result =
      QualificationResult.find(params[:qualification_result_id])
    @qualification_result.position = params[:qualification_result][:position]
    time = params[:qualification_result][:time]
    @qualification_result.time = if time != ''
                                   if time.include? ':'
                                     '00:' + time
                                   else
                                     '00:00:' + time
                                   end
                                 else
                                   '00:00:00,000'
                                 end
    respond_to do |format|
      if @qualification_result.save
        format.html {
          redirect_to qualification_series_season_round_path(@round.season.serie, @round.season, @round),
                      notice: 'Zaktualizowano rezultat.'
        }
        format.json { render :show_qualification, status: :ok, location: @round }
      else
        format.html {
          flash.now.alert = @serie.errors.full_messages.join('<br />').html_safe
          render :edit_qualification_result
        }
        format.json { render json: @qualification_result.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_races
    if not(@round.teams.empty?) && not(@round.qualification.nil?) && not(@round.qualification.qualification_results.empty?)
      if @round.race_groups.empty? && user_signed_in?
        create_race_groups
      end
      if not(@round.race_groups.empty?) && @round.races.empty? &&
          user_signed_in?
        create_races
      end

      unless @round.race_groups.empty?
        @races = @round.races

        @races_groups = @round.race_groups

        @season = @round.season

        respond_to do |format|
          return render :races
        end
      end
    end

    if user_signed_in?
      flash[:alert] = 'Brak zgłoszonych zespołów.'
    end
    redirect_to starting_teams_series_season_round_path(
                  @round.season.serie, @round.season, @round
                )
  end

  def edit_race_result
    @race_result = RaceResult.find(params[:race_result_id])
  end

  def update_race_result
    @race_result = RaceResult.find(params[:race_result_id])
    @race_result.points = params[:race_result][:points]
    respond_to do |format|

app/helpers/rounds_helper.rb
# frozen_string_literal: true

module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_with(model: round, local: true) do |form| %>
  <% if round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
        <% round.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :track_name %>
    <%= form.text_field :track_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :max_number_of_carts %>
    <%= form.number_field :max_number_of_carts %>
  </div>

  <div class="field">
    <%= form.label :ended_races_counter %>
    <%= form.number_field :ended_races_counter %>
  </div>

  <div class="field">
    <%= form.label :season_id %>
    <%= form.text_field :season_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<% errors = @round.errors.messages %>
<% saved_round = Round.find(@round.id) %>
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"), series_season_round_path(@round.season.serie, @round.season, @round),
          method: :get, class: "btn btn-light btn-sm" %>
        <%= saved_round.name %> - edycja
      </div>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= form_for @round, url: series_season_round_path(@round.season.serie, @round.season, @round),
            html: { method: :patch } do |f| %>
          <div class="form-group">
            <%= f.label :name, "Nazwa rundy" %>
            <%= f.text_field :name, class: "form-control" %>
            <% if errors[:name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :track_name, "Nazwa toru" %>
            <%= f.text_field :track_name, class: "form-control" %>
            <% if errors[:track_name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[track_name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :address, "Adres" %>
            <%= f.text_area :address, class: "form-control" %>
            <% if errors[:address].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[address].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :start_time, "Czas rozpoczęcia" %>
            <%= f.datetime_local_field :start_time, class: "form-control",
                pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:00$",
                title: "rrrr-MM-ddThh:mm:00." %>
            <% if errors[:start_time].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[start_time].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :price, "Cena wpisowego" %>
            <%= f.text_field :price, class: "form-control",
                pattern: "^[0-9]+(,[0-9]{1,2})? [A-Z]{3}$",
                title: "12,67 PLN." %>
            <% if errors[:price].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:price].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :max_number_of_carts, "Maksymalna liczba gokartów na torze" %>
            <%= f.number_field :max_number_of_carts, min: 1, step: 1,
                class: "form-control" %>
            <% if errors[:max_number_of_carts].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:max_number_of_carts].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
          </div>
          
          <div style="text-align: center;">
            <%= f.submit "Zapisz", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to "Wróć", series_season_round_path(params[:series_id], params[:season_id], params[:id]) %>
      </div>
      <div class="col-auto m button-header">
        <%= button_to "Usuń rundę", series_season_round_path(@round.season.serie, @round.season, @round),
            method: :delete, class: "btn btn-danger btn-sm",
            data: { confirm: "Czy na pewno chcesz usunąć rundę <strong>" +
                saved_round.name + "</strong>?" } %>
      </div>
    </div>
  </div>
</div>

app/views/rounds/edit_cart.html.erb
<% errors = @cart.errors.messages %>
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"), carts_series_season_round_path(@round.season.serie, @round.season, @round),
          method: :get, class: "btn btn-light btn-sm" %>
        <%= "Gokart #" + @cart.number.to_s %> - edycja
      </div>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= form_for @cart, url: cart_series_season_round_path(@round.season.serie, @round.season, @round, @cart),
            html: { method: :patch } do |f| %>
          <div class="form-group">
            <%= f.label :number, "Numer" %>
            <%= f.number_field :number, class: "form-control", min: 0, step: 1 %>
            <% if errors[:number].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:number].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            <br />
            <div class="custom-control custom-checkbox"
                style="text-align: center;">
              <% name = "cart[special]" %>
              <%= check_box_tag name, "true", @cart.special,
                  class: "custom-control-input" %>
              <%= label_tag name, "Specjalny?",
                  class: "custom-control-label" %>
            </div>
            <br />
          </div>
          <div style="text-align: center;">
            <%= f.submit "Zapisz", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to "Wróć", series_season_round_path(params[:series_id], params[:season_id], @round) %>
      </div>
      <div class="col-auto m button-header">
        <%= button_to "Usuń gokart", cart_series_season_round_path(@round.season.serie, @round.season, @round, @cart),
            method: :delete, class: "btn btn-danger btn-sm",
            data: { confirm: "Czy na pewno chcesz usunąć gokart <strong>#" +
                @cart.number.to_s + "</strong>?" } %>
      </div>
    </div>
  </div>
</div>

app/views/rounds/new.html.erb
<% errors = @round.errors.messages %>
<div class="card card-app">
  <h5 class="card-header">
    Nowa runda
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        
        <%= form_for @round, url: series_season_rounds_path,
            html: { method: :post } do |f| %>
          <div class="form-group">
            <%= f.label :name, "Nazwa rundy" %>
            <%= f.text_field :name, class: "form-control" %>
            <% if errors[:name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :track_name, "Nazwa toru" %>
            <%= f.text_field :track_name, class: "form-control" %>
            <% if errors[:track_name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[track_name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :address, "Adres" %>
            <%= f.text_area :address, class: "form-control" %>
            <% if errors[:address].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[address].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :start_time, "Czas rozpoczęcia" %>
            <%= f.datetime_local_field :start_time, class: "form-control",
                pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:00$",
                title: "Data i czas w formacie \"rrrr-MM-ddThh:mm:00\"." %>
            <% if errors[:start_time].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[start_time].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :price, "Cena wpisowego" %>
            <%= f.text_field :price, class: "form-control",
                pattern: "^[0-9]+(,[0-9]{1,2})? [A-Z]{3}$",
                title: "Cena w formacie \"12,67 PLN\"." %>
            <% if errors[:price].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:price].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            
            <%= f.label :max_number_of_carts, "Maksymalna liczba gokartów na torze" %>
            <%= f.number_field :max_number_of_carts, value: 10, min: 1, step: 1,
                class: "form-control" %>
            <% if errors[:max_number_of_carts].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:max_number_of_carts].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
          </div>
          
          <div style="text-align: center;">
            <%= f.submit "Utwórz", class: "btn btn-success" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
  <div class="card-footer text-muted">
    <%= link_to "Wróć",
        series_season_path(params[:series_id], params[:season_id]) %>
  </div>
</div>

app/views/rounds/new_cart.html.erb
<% errors = @cart.errors.messages %>
<div class="card card-app">
  <h5 class="card-header">
    <%= @round.name + " - Nowy gokart" %>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        
        <%= form_for @cart, url: new_cart_series_season_round_path(@round.season.serie, @round.season, @round),
            html: { method: :post } do |f| %>
          <div class="form-group">
            <%= f.label :number, "Numer" %>
            <%= f.number_field :number, class: "form-control", min: 0, step: 1 %>
            <% if errors[:number].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:number].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
            <br />
            <div class="custom-control custom-checkbox"
                style="text-align: center;">
              <% name = "cart[special]" %>
              <%= check_box_tag name, "true", @cart.special,
                  class: "custom-control-input" %>
              <%= label_tag name, "Specjalny?",
                  class: "custom-control-label" %>
            </div>
            <br />
          </div>
          
          <div style="text-align: center;">
            <%= f.submit "Utwórz", class: "btn btn-success" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
  <div class="card-footer text-muted">
    <%= link_to "Wróć", :back %>
  </div>
</div>

app/views/rounds/show.html.erb
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"), series_season_path(@round.season.serie, @round.season), method: :get,
            class: "btn btn-light btn-sm" %>
        <%= @round.season.serie.name + " - " + @round.season.name + " - " + @round.name %>
      </div>
      <div class="col-auto m button-header">
        <%= button_to "Lista startowa", starting_teams_series_season_round_path(@round.season.serie, @round.season, @round),
            method: :get, class: "btn btn-primary btn-sm" %>
      </div>
      <div class="col-auto m button-header">
        <%= button_to "Gokarty", carts_series_season_round_path(@round.season.serie, @round.season, @round),
            method: :get, class: "btn btn-primary btn-sm" %>
      </div>
      <% if user_signed_in? %>
        <% if @round.qualification.nil? %>
          <div class="col-auto m button-header">
            <%= button_to "Rozpocznij kwalifikacje", qualification_series_season_round_path(@round.season.serie, @round.season, @round),
                method: :get, class: "btn btn-success btn-sm" %>
          </div>
        <% end %>
        <% if @round.races.empty? && not(@round.qualification.nil?) &&
            not(@round.qualification.qualification_results.empty?) %>
          <div class="col-auto m button-header">
            <%= button_to "Rozpocznij wyścigi", races_series_season_round_path(@round.season.serie, @round.season, @round),
                method: :get, class: "btn btn-success btn-sm" %>
          </div>
        <% end %>
        <div class="col-auto m button-header">
          <%= button_to "Edytuj rundę", edit_series_season_round_path(@round.season.serie, @round.season, @round),
              method: :get, class: "btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </h5>
  <div class="card-body text-center" style="overflow-y: auto">
    <div class="list-group">
      <h3 class="card-title">
        Tor:<br />
        <strong><%= @round.track_name %></strong>
      </h3>
      <h4 class="card-text">
        Termin:<br />
        <strong><%= @round.start_time.strftime("%d.%m.%Y, godz. %H:%M") %></strong>
      </h4>
      <h5 class="card-text">
        Cena wpisowego:<br />
        <strong><%= @round.price %></strong>
      </h5>
      <p class="card-text">
        Adres:<br />
        <strong><%= (@round.address.gsub "\n", "<br />").html_safe %></strong>
      </p>
      <p class="card-text">
        Maksymalna liczba gokartów:<br />
        <strong><%= @round.max_number_of_carts %></strong>
      </p>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to "Wróć", :back %>
      </div>
      <% unless @round.round_results.empty? %>
        <div class="col-auto m button-header">
              <%=  button_to "Wyniki", results_series_season_round_path(@round.season.serie, @round.season, @round),
                method: :get, class: "btn btn-primary btn-sm"  %>
        </div>
      <%  end %>
      <% unless @round.races.empty? %>
        <div class="col-auto m button-header">
              <%=  button_to "Wyścigi", races_series_season_round_path(@round.season.serie, @round.season, @round),
                method: :get, class: "btn btn-primary btn-sm"  %>
        </div>
      <%  end %>
      <% unless @round.qualification.nil? %>
        <div class="col-auto m button-header">
              <%=  button_to "Kwalifikacje", qualification_series_season_round_path(@round.season.serie, @round.season, @round),
                method: :get, class: "btn btn-primary btn-sm"  %>
        </div>
      <%  end %>
    </div>
  </div>
</div>

app/views/rounds/show_carts.html.erb
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"),
            series_season_round_path(@round.season.serie, @round.season, @round),
            method: :get,
            class: "btn btn-light btn-sm" %>
        <%= @round.name %> - lista gokartów
      </div>
      <% if user_signed_in? %>
        <div class="col-auto m button-header">
          <%= button_to "Dodaj gokart", new_cart_series_season_round_path(@round.season.serie, @round.season, @round),
              method: :get, class: "btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto;">
    <div class="row justify-content-center">
      <div class="col-auto">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Specjalny?</th>
                <% if user_signed_in? %>
                  <th scope="col"></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @round.carts.sort_by {
                    |rc| rc.number
                  }.each do |cart| %>
                <tr>
                  <div class="form-group">
                    <th scope="row"><%= cart.number %></th>
                    <td>
                      <div class="custom-control custom-checkbox"
                          style="text-align: center;">
                        <% name = "carts[" + cart.id.to_s + "][special]" %>
                        <%= check_box_tag name, "true", cart.special,
                            disabled: true,
                            class: "custom-control-input" %>
                        <%= label_tag name, "",
                            class: "custom-control-label" %>
                      </div>
                    </td>
                    <% if user_signed_in? %>
                      <td>
                        <div class="col-auto m button-header">
                          <%= button_to "Edytuj gokart",
                              cart_series_season_round_path(@round.season.serie, @round.season, @round, cart),
                              method: :get, class: "btn btn-primary btn-sm" %>
                        </div>
                      </td>
                    <% end %>
                  </div>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to "Wróć", :back %>
  </div>
</div>