config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :series do
    resources :seasons, except: [:index] do
      resources :rounds, except: [:index] do
        member do
          get 'starting_teams' => 'rounds#edit_teams'
          patch 'starting_teams' => 'rounds#update_teams'
          get 'qualification' => 'rounds#show_qualification'
          get 'qualification_group_result/:qualification_group_result_id' => 'rounds#edit_qualification_group_result', as: :qualification_group_result
          patch 'qualification_group_result/:qualification_group_result_id' => 'rounds#update_qualification_group_result'
          get 'qualification_generate_result' => 'rounds#generate_qualification_result'
          get 'qualification_result/:qualification_result_id' => 'rounds#edit_qualification_result', as: :qualification_result
          patch 'qualification_result/:qualification_result_id' => 'rounds#update_qualification_result'
          get 'races' => 'rounds#show_races'
          get 'race_result/:race_result_id' => 'rounds#edit_race_result', as: :race_result
          patch 'race_result/:race_result_id' => 'rounds#update_race_result'
          get 'carts' => 'rounds#show_carts'
          get 'cart/:cart_id' => 'rounds#edit_cart', as: :cart
          patch 'cart/:cart_id' => 'rounds#update_cart'
          delete 'cart/:cart_id' => 'rounds#destroy_cart'
          get 'new_cart' => 'rounds#new_cart', as: :new_cart
          post 'new_cart' => 'rounds#create_cart'
          get 'results' => 'rounds#show_results'
        end
      end
      resources :teams, except: [:show]
    end
  end
  devise_for :users, skip: [:confirmation, :passwords, :registrations]
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/series_controller.rb
# frozen_string_literal: true

class SeriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @content_0 = '<div class="d-flex justify-content-between">' +
        '<h5 class="mb-1">'
    @content_1 = '</h5><small style="allign: right;">Zakończone sezony: '
    @content_2 = '</small></div>'
    @content_3 = '<small>Liczba sezonów: '
    @content_4 = '</small>'
    @series = Serie.all.sort_by { |s| s.name.downcase }
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @seasons = @serie.seasons.sort_by { |s| s.name.downcase }
    
    @content_0 = '<div class="d-flex justify-content-between">' +
        '<h5 class="mb-1">'
    @content_1 = '</h5><small style="allign: right;">Zakończone rundy: '
    @content_2 = '</small></div>'
    @content_3 = '<small>Liczba rund: '
    @content_4 = '</small>'
  end

  # GET /series/new
  def new
    @serie = Serie.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    begin
      @serie = Serie.new(series_params)
  
      respond_to do |format|
        if @serie.save
          format.html { redirect_to @serie, notice: 'Stworzono nową serię.' }
          format.json { render :show, status: :created, location: @serie }
        else
          format.html { render :new }
          format.json { render json: @serie.errors, status: :unprocessable_entity }
        end
      end
		rescue ActiveRecord::RecordNotUnique
			respond_to do |format|
				flash.now.alert = 'Seria o tej nazwie już istnieje.'
				return render :new
			end
		rescue ActiveRecord::RecordInvalid
			respond_to do |format|
			  flash.now.alert = @season.errors.full_messages.join('<br />').html_safe
			 # @form_class = "needs-validation was-validated"
			  return render :new
			end
		end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    begin
      respond_to do |format|
        if @serie.update(series_params)
          format.html { redirect_to @serie, notice: 'Zmieniono nazwę serii.' }
          format.json { render :show, status: :ok, location: @serie }
        else
          format.html {
            flash.now.alert = @serie.errors.full_messages.join('<br />').html_safe
            render :edit
          }
          format.json { render json: @serie.errors, status: :unprocessable_entity }
        end
      end
		rescue ActiveRecord::RecordNotUnique
			respond_to do |format|
				flash.now.alert = 'Seria o tej nazwie już istnieje.'
				return render :edit
			end
		rescue ActiveRecord::RecordInvalid
			respond_to do |format|
			  flash.now.alert = @season.errors.full_messages.join('<br />').html_safe
			  return render :edit
			end
		end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @serie.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Usunięto serię.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @serie = Serie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:serie).permit(:name)
    end
end

app/helpers/series_helper.rb
# frozen_string_literal: true

module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_with(model: series, local: true) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<% errors = @serie.errors.messages %>
<% saved_serie = Serie.find(@serie.id) %>
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"), series_path(@serie), method: :get,
            class: "btn btn-light btn-sm" %>
        <%= saved_serie.name %> - edycja
      </div>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= form_for @serie, url: series_path(@serie),
            html: { method: :patch } do |f| %>
          <div class="form-group">
            <%= f.label :name, "Nazwa serii" %>
            <%= f.text_field :name, class: "form-control" %>
            <% if errors[:name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
          </div>
          
          <div style="text-align: center;">
            <%= f.submit "Zapisz", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to "Wróć", :back %>
      </div>
      <div class="col-auto m button-header">
        <%= button_to "Usuń serię", series_path(@serie), method: :delete,
            class: "btn btn-danger btn-sm",
            data: { confirm: "Czy na pewno chcesz usunąć serię <strong>" +
                saved_serie.name + "</strong>?" } %>
      </div>
    </div>
  </div>
</div>

app/views/series/index.html.erb
<div class="card card-app">
  <h5 class="card-header">
    <div class="container">
      <div class="row">
        <div class="col-auto mr-auto">
          Serie
        </div>
        <% if user_signed_in? %>
          <div class="col-auto m button-header">
            <%= button_to "Stwórz serię", new_series_path,
                method: :get, class: "btn btn-primary btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="list-group">
      <% @series.sort_by{ |s| s.name }.each do |serie| %>
        <% content = @content_0 + serie.name + @content_1 +
            serie.ended_seasons_counter.to_s + @content_2 + @content_3 +
            serie.seasons.size.to_s + @content_4 %>
        <%= link_to content.html_safe, series_path(serie), method: :get,
            class: "list-group-item list-group-item-action" %>
      <% end %>
    </div>
  </div>
</div>

app/views/series/new.html.erb
<% errors = @serie.errors.messages %>
<div class="card card-app">
  <h5 class="card-header">
    Nowa seria
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="row justify-content-center">
      <div class="col-auto">
        
        <%= form_for @serie, url: series_index_path,
            html: { method: :post } do |f| %>
          <div class="form-group">
            <%= f.label :name, "Nazwa serii" %>
            <%= f.text_field :name, class: "form-control" %>
            <% if errors[:name].length > 0 %>
              <div class="error_message">
                <%= ("Pole " + errors[:name].join("<br />Pole ")).html_safe %>
              </div>
            <% end %>
          </div>
          
          <div style="text-align: center;">
            <%= f.submit "Utwórz", class: "btn btn-success" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
  <div class="card-footer text-muted">
    <%= link_to "Wróć", :back %>
  </div>
</div>

app/views/series/show.html.erb
<div class="card card-app">
  <h5 class="card-header">
    <div class="row">
      <div class="col-auto mr-auto">
        <%= link_to (fa_icon "chevron-left"), series_index_path, method: :get,
            class: "btn btn-light btn-sm" %>
        <%= @serie.name %>
      </div>
      <% if user_signed_in? %>
        <div class="col-auto m button-header">
          <%= button_to "Dodaj sezon", new_series_season_path(@serie),
              method: :get, class: "btn btn-success btn-sm" %>
        </div>
        <div class="col-auto m button-header">
          <%= button_to "Edytuj serię", edit_series_path(@serie),
              method: :get, class: "btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </h5>
  <div class="card-body" style="overflow-y: auto">
    <div class="list-group">
      <% @seasons.sort_by{ |s| s.name }.each do |season| %>
        <% content = @content_0 + season.name + @content_1 +
            season.ended_rounds_counter.to_s + @content_2 + @content_3 +
            season.rounds.size.to_s + @content_4 %>
        <%= link_to content.html_safe, series_season_path(season.serie, season),
            method: :get,
            class: "list-group-item list-group-item-action" %>
      <% end %>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to "Wróć", :back %>
  </div>
</div>